/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DataFromApiImport } from './routes/data-from-api'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DataFromApiRoute = DataFromApiImport.update({
  id: '/data-from-api',
  path: '/data-from-api',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/data-from-api': {
      id: '/data-from-api'
      path: '/data-from-api'
      fullPath: '/data-from-api'
      preLoaderRoute: typeof DataFromApiImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-from-api': typeof DataFromApiRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-from-api': typeof DataFromApiRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/data-from-api': typeof DataFromApiRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data-from-api'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data-from-api'
  id: '__root__' | '/' | '/data-from-api'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataFromApiRoute: typeof DataFromApiRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataFromApiRoute: DataFromApiRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/data-from-api"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/data-from-api": {
      "filePath": "data-from-api.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
